In [57]:
import mglearn
import numpy as np 
import pandas as pd 
import seaborn as sb 
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import warnings
warnings.simplefilter('ignore')

Problem of XOR

In [68]:
x_data = np.array( [[0,0],[0,1],[1,0],[1,1]])
y_data = np.array( [[0],[1],[1],[0]])

In [69]:
model_logi =  LogisticRegression( )
model_logi.fit( x_data, y_data )

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [70]:
model_logi.coef_

array([[0., 0.]])

In [71]:
model_logi.score( x_data, y_data )

0.5

In [72]:
model_logi.predict( x_data )

array([0, 0, 0, 0])

Solution

In [86]:
model = MLPClassifier()
model.fit( x_data, y_data )

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [87]:
model.score( x_data, y_data )

1.0

In [88]:
model.predict( x_data )

array([0, 1, 1, 0])

In [89]:
model.coefs_

[array([[ 1.25512920e-02,  7.61327151e-03, -5.76812599e-02,
         -3.00041050e-04, -2.06814714e-01, -1.46955843e-01,
         -2.65537634e-01, -2.29738803e-01, -1.69431696e-02,
         -1.50855001e-02,  2.57690072e-01, -3.35449125e-01,
         -1.71542333e-01,  3.74204465e-01,  2.47226905e-01,
         -2.55457726e-07,  2.59875339e-02, -9.62851265e-02,
         -7.10397016e-02, -6.65340140e-03, -4.82215526e-02,
          1.37395169e-01,  2.05960461e-07, -2.44999823e-01,
         -2.42892705e-01,  1.56070939e-01, -3.86352988e-02,
          2.68187911e-02,  1.13458512e-01, -7.85663619e-02,
         -3.17770508e-02,  3.82078446e-02,  2.58769680e-01,
          2.78174868e-01, -1.67753434e-01, -1.82230853e-01,
          1.75462845e-01, -5.24753264e-02, -1.75214039e-01,
          2.14319022e-01,  2.82403447e-01, -5.39054990e-06,
         -6.21646228e-02, -1.63188848e-02, -1.24993934e-01,
         -1.79228598e-03,  2.85579706e-01,  2.28610250e-01,
         -2.36936124e-01,  2.15063311e-0

In [90]:
model.coefs_[0].shape     # feature의 개수가 2이므로 2로 나옴. [4 by 2] [2 by 100] = [4 by 100 ] 

(2, 100)

In [98]:
a = np.matmul( x_data, model.coefs_[0] ) + model.intercepts_[0]
# a => ReLU(Rectified Linear Unit, 경사함수) 함수 통과 시킬 필요가 있음.
b = np.matmul( a,  model.coefs_[1] ) + model.intercepts_[1]
# b => 이진 분류인 경우 마지막 output layer은 sigmoid 함수 통과 시킬 필요가 있음.
b.shape

(4, 1)

In [80]:
 model.intercepts_[0].shape  # bias를 100개 더해줌.

(100,)

In [81]:
model.coefs_[1].shape    # [4 by 100 ] [100 by 1] = [4 by 1]

(100, 1)

In [82]:
 model.intercepts_[1].shape  # bias를 1개 더해줌.

(1,)

In [83]:
model.predict( x_data ).shape   #  최종적으로 [4 by 1]

(4,)

In [16]:
len( model.intercepts_ )

2

In [17]:
model = MLPClassifier(hidden_layer_sizes=(200,5))
model.fit( x_data, y_data )

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(200, 5), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [18]:
len( model.coefs_ )    
# len( model.coefs_ ) - 1 => hidden layer 개수, 제약되는 1개는 output layer 

3

In [19]:
model.coefs_[0].shape       
# feature의 개수가 2이므로 2로 나옴. [4 by 2](input layer) [2 by 200](hidden layer) = [4 by 200 ] (weighted value)

(2, 200)

In [20]:
model.coefs_[1].shape       
# feature의 개수가 2이므로 2로 나옴. [4 by 200] [200 by 5](hidden layer) = [4 by 5 ] (weighted value)

(200, 5)

In [21]:
model.coefs_[2].shape      
# [4 by 5 ](weighted value) [5 by 1](output layer) = [4 by 1]

(5, 1)

In [22]:
model.predict( x_data ).shape 

(4,)

In [23]:
model = MLPClassifier(hidden_layer_sizes=(200, 10, 6))  # => hidden layer : feature의 수 X 200, 200 X 10, 10 X 6
model.fit( x_data, y_data )                             # => ouput layer : 6 X label의 수

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(200, 10, 6), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [24]:
len( model.coefs_ )
# len( model.coefs_ ) - 1 => hidden layer 개수, 제약되는 1개는 output layer => hidden layer 3개다. 

4

In [25]:
model.coefs_[0].shape
# feature의 개수가 2이므로 2로 나옴. 데이터의 형태가 4 by 2
# [4 by 2](input layer) [2 by 200](hidden layer) = [4 by 200 ] (weighted value)

(2, 200)

In [26]:
 model.intercepts_[0].shape

(200,)

In [27]:
model.coefs_[1].shape       
# feature의 개수가 2이므로 2로 나옴. [4 by 200] [200 by 10](hidden layer) = [4 by 10 ] (weighted value)

(200, 10)

In [28]:
 model.intercepts_[1].shape

(10,)

In [29]:
model.coefs_[2].shape 
# [4 by 10 ](weighted value) [10 by 6](hidden layer) = [4 by 6]

(10, 6)

In [30]:
 model.intercepts_[2].shape

(6,)

In [31]:
model.coefs_[3].shape 
# [4 by 6 ](weighted value) [6 by 1](output layer) = [4 by 1]

(6, 1)

In [32]:
 model.intercepts_[3].shape

(1,)

In [33]:
model.predict( x_data ).shape 
# 결국은 최종 예측값은 y_data의 행렬 행태로 나올 것이다.

(4,)

In [60]:
model = MLPClassifier( hidden_layer_sizes=(100, 50, 30, 20) )
model.fit( x_data, y_data )    
# => hidden layer : feature의 수 X 100, 100 X 50, 50 X 30, 30 x 20
# => ouput layer : 20 X label의 수

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100, 50, 30, 20), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [61]:
len( model.coefs_ ) - 1

4

In [62]:
model.coefs_[0].shape, model.intercepts_[0].shape

((2, 100), (100,))

In [63]:
model.coefs_[1].shape, model.intercepts_[1].shape

((100, 50), (50,))

In [64]:
model.coefs_[2].shape, model.intercepts_[2].shape

((50, 30), (30,))

In [65]:
model.coefs_[3].shape, model.intercepts_[3].shape

((30, 20), (20,))

In [66]:
model.coefs_[4].shape, model.intercepts_[4].shape

((20, 1), (1,))

In [67]:
model.predict( x_data ), model.score( x_data, y_data )

(array([0, 1, 1, 0]), 1.0)